### ISSUE TITLE
Use data attributes with json to allow single quotes

### ISSUE THREAD

**Issue by jenstornell** [floriankarsten/kirby-tablex#5]
You wrote about a problem with single quotes and I think a combination with data attributes and json is a good way. I've used it myself before.

https://stackoverflow.com/questions/35634624/json-object-in-data-attribute

I modified this fiddle and added a single quote just to show that it works.

https://jsfiddle.net/b1tqxhty/7/

**Comment by krisak** [comment]
Thanks, the problem was actually how to put it into the data-attribute properly from php. But this issue reminded me that i should do something about it.

Ive switched 
```php
a::json($field->value()['tables']);
```
to 
```php
htmlspecialchars(json_encode($field->value()['tables']), ENT_QUOTES, 'UTF-8');
```
Seems it fixed the issue.

**Comment by krisak** [comment]
Ive also noticed i made stupid name for the table array (tables). Sigh i should fix that too.

**Comment by krisak** [comment]
Both fixed. Maybe i can close this?
