### ISSUE TITLE
Infinite columns?

### ISSUE THREAD

**Issue by janstieler** [floriankarsten/kirby-tablex#7]
Hi,
actually I have to set the maximum Columns.
But how can I allow infinite columns?
Yes I can set it to 999999. But I think it would be better if this option is only necessary if I want to restrict the columns.

Cheers

**Comment by krisak** [comment]
Sorry for late reply.

Well it is not sensible to have unlimited columns no? We have not implemented any kind of scrolling of the colums so realisticaly you can fit max like 20 columns.

Why do you need this feature?

**Comment by janstieler** [comment]
Hi,
no problems.
This questions comes up because I have here a situation with a table who had a lot of information.
In this szenario I saw that limitation and asked my self why its necessary to restrict that?
Also it was more a question than a reallife demand.

**Comment by krisak** [comment]
Well my thinking was that it is always good idea to limit user input. In my case i want to show those tables on website. If i leave users to make 40column table i wont be able to show it anyway. If i limit them to 10 columns they will work around it and maybe structure it in much better way so they dont need 40 columns.

It is design decision.

But honestly i don't know i thought nobody uses the field so i don't pay too much attention to it. I use it on few of my websites and made it so it works for my purpose. If you need some functionality and can't make it yourself (i understand that it is done in a  uncommon way in kirby land using vue.js) give me good reasons and i might fix it.

**Comment by janstieler** [comment]
Thanks for your offer but I think for this function ist is not really neccessary. As I mentioned it was an spark in my head and I asked :).
