### ISSUE TITLE
Plugin folder installation

### ISSUE THREAD

**Issue by janstieler** [floriankarsten/kirby-tablex#8]
Hi,
you wrote that the plugin have to install in the plugin folder.
If you do this you get the error 
> Class 'BaseField' not found 
BaseField is only available in the field folder I think.

Cheers

**Comment by krisak** [comment]
You are totaly right. I copied the readme from somewhere else and it should be in fields. Strange nobody has noticed this before.

**Comment by krisak** [comment]
Fixed in docs
